apply plugin: 'com.android.library'

android {
    compileSdk 35

    defaultConfig {
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName "1.4.6"

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    
    namespace 'me.aflak.arduino'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'androidx.appcompat:appcompat:1.6.1'

    api 'com.github.felHR85:UsbSerial:6.1.0'
}
